### ISSUE TITLE
Revamp games index

### ISSUE THREAD

**Issue by grmnlrt** [grmnlrt/maxime-herve.com#26]
I saw Max this evening. We need to uniformise `movies#index` and `games#index`.

Can you try to reuse the CSS made for `movies#index` for the video games 🙏

I think the best will be to rename [this file](https://github.com/grmnlrt/maxime-herve.com/blob/master/app/assets/stylesheets/components/_movie_card.scss) and all the classes into it to express that this CSS is dedicated to the movies, and to the video games as well (maybe just `card`, or something like `project-card`, try to find the most relevant name)

**Comment by grmnlrt** [comment]
Also, games should be sorted by release date in descending order.

**Comment by benjyarel** [comment]
Ok , time to refacto ! :) .

**Comment by benjyarel** [comment]
Refacto done I'm just waiting for Maxime feedback about the "black box" in indexes . If we want to have the same design, we need a information in it, but witch one ?  ( genre, developper, role .. ect)
