### ISSUE TITLE
Create page info

### ISSUE THREAD

**Issue by grmnlrt** [grmnlrt/maxime-herve.com#29]
The content is already on the page, but there is no design at the moment.

First step here will be to draw a simple figma for desktop and mobile.

**Comment by svilder** [comment]
I tried to put some text styling into these plain texts boxes... 
https://www.figma.com/file/nqJn1Q8xTcQ082pdGK8SUk/Maxime-Herv%C3%A9?node-id=0%3A1

**Comment by grmnlrt** [comment]
I like the idea of two columns layout for the text 👍(maybe just remove the tabulation a the beginning of the paragraph it's a bit too old school).

For the rewards, I prefer the first version but I think we need to further.
Try to add more contrast between the date and the reward name.
And maybe group reward by year and add some space between each year.

**Comment by grmnlrt** [comment]
![](https://customercare.igloosoftware.com/.api2/binaries/nYHA8UxOhz/thumbnails/whatisit2.png?width=600)

It's obviously not the good design, but maybe something like that with the year instead of the date and the list of reward for this year (without the lines and with the year on the left)

**Comment by svilder** [comment]
Ok, I tried two other version. What do you think ? 
https://www.figma.com/file/nqJn1Q8xTcQ082pdGK8SUk/Maxime-Herv%C3%A9?node-id=0%3A1

**Comment by grmnlrt** [comment]
More something like this quick sketch 👇 (with a column for years and a column for rewards)

<img width="981" alt="Screenshot 2020-01-24 at 10 35 36" src="https://user-images.githubusercontent.com/25386941/73059191-760f8800-3e95-11ea-9369-c5ac39305d71.png">

**Comment by svilder** [comment]
Got it. https://www.figma.com/file/nqJn1Q8xTcQ082pdGK8SUk/Maxime-Herv%C3%A9?node-id=0%3A1

I think I prefer the second one. No indentation on Rewards title.

**Comment by grmnlrt** [comment]
Agreed! No indentation for the title and no border for dates 👌
And for the mobile view you can get rid of the columns, just put the date centered upside each blocks.

I think you can start to build it 🙌
