### ISSUE TITLE
Create Movies index

### ISSUE THREAD

**Issue by grmnlrt** [grmnlrt/maxime-herve.com#7]
- [x] Create route and controller action
- [x] Use Bootstrap for page structure
- [x] Create `movie-card`component to list Movies
- [x] Make it responsive

Max's figma:
<img width="855" alt="Screenshot 2019-12-27 at 13 12 50" src="https://user-images.githubusercontent.com/25386941/71516707-bab1fe80-28aa-11ea-9e72-a19726d16daa.png">

**Comment by benjyarel** [comment]
If we want to sort movies and games by publishing date, maybe it'll be usefull to add a month? 
We could this way use : @movies = Movie.all.order(year, :desc).
Unless this, all movies in the same years won't be sorted

**Comment by grmnlrt** [comment]
> If we want to sort movies and games by publishing date, maybe it'll be usefull to add a month?
> We could this way use : @movies = Movie.all.order(year, :desc).
> Unless this, all movies in the same years won't be sorted

Don't know if it's a behavior that Max wants. Let's keep it ordered by default for the moment and we'll ask him if he wants a specific order.
