### ISSUE TITLE
Create Games index

### ISSUE THREAD

**Issue by grmnlrt** [grmnlrt/maxime-herve.com#8]
- [x] Create route and controller action
- [x] Use Bootstrap for page structure
- [x] Create `game-card`component to list Games
- [x] Make it responsive

Max's figma:
<img width="845" alt="Screenshot 2019-12-27 at 13 12 37" src="https://user-images.githubusercontent.com/25386941/71516724-da492700-28aa-11ea-90fe-3db57680ba21.png">

**Comment by benjyarel** [comment]
@grmnlrt  Hey !  

We need to add a column in the db: "genre: string".
also :  "date de sortie", must be a string, not a year: integer ( eg: "tba", " 2 octobre 2018")
Is it ok for you, i'm changing the games table ?
